# Generated by Django 4.2.4 on 2023-11-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('actorname', models.CharField(max_length=30)),
                ('actorphoto', models.ImageField(default='null.jpeg', upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songartist', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('moviedisciption', models.CharField(max_length=150)),
                ('moviecategory', models.CharField(max_length=20)),
                ('movieposter', models.ImageField(default='null.jpeg', upload_to='movies')),
                ('movievideo', models.FileField(default='null.mp4', upload_to='movies')),
                ('imdbrating', models.FloatField(default=0)),
                ('moviedirector', models.CharField(default='null', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Smovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songmovie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=30)),
                ('songmovie', models.CharField(max_length=150)),
                ('songcategory', models.CharField(max_length=20)),
                ('songartist', models.CharField(max_length=200)),
                ('songposter', models.ImageField(default='null.jpeg', upload_to='movies')),
                ('song', models.FileField(default='null.mp3', upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.IntegerField()),
                ('confirmpassword', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('subscription', models.CharField(max_length=10)),
                ('profilephoto', models.ImageField(default='null.jpeg', upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.movies')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.users')),
            ],
        ),
    ]
